# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aangan_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uid',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='scoringschema',
            name='uid',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
